kind: pipeline
type: docker
name: drone-cloud-test-for-python3

steps:
- name: backend
  image: python:latest
  commands:
  - pip3 install -r requirements.txt
  - cd src
  - python -m pytest ../tests  
- name: discord
  image: appleboy/drone-discord
  when:
    event: [ push, tag]
    status: [ changed, failure, success ]
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
    message: >
      > #{{build.number}} {{repo.name}}/{{commit.branch}}

      > drone cloud link: {{build.link}}

      > 操作: {{build.event}}

      > ユーザー: {{commit.author}}

      コミットメッセージ: 

      ```{{commit.message}}```

      > 結果:
    
      {{#success build.status}}
      > `テストをすべて通過しました！よかったな…で…それが何の役に立つ！`

      https://imgur.com/goGskeC
      {{else}}
      > `おっと！テストを通過できなかったようです・・・まだまだ心眼が足らぬ。`

      https://imgur.com/OFuiEjW
      {{/success}} 


      