version: "2"
services:
  web:
    build: .
    ports:
      - "4649:4649"
    mem_limit: 1g
    volumes:
      - ..:/workspace
    environment:
      TZ: "Asia/Tokyo"
    command: "sleep infinity"