# Generated by Django 3.0.6 on 2020-05-20 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.CharField(default='system', max_length=31)),
                ('updated_at', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'verbose_name': '学科',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('enrollment_class', models.IntegerField(default=None, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.CharField(default='しす', max_length=31)),
                ('updated_at', models.CharField(blank=True, max_length=31, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Subject')),
            ],
            options={
                'verbose_name': 'ユーザー',
            },
        ),
    ]
